---
include:
  - component: "gitlab.gnome.org/GNOME/citemplates/release-service@master"
    inputs:
      job-stage: "release"
      dist-job-name: "build-distcheck"
      tarball-artifact-path: "${TARBALL_ARTIFACT_PATH}"

variables:
  TARBALL_ARTIFACT_PATH: "bootstrapped/${CI_PROJECT_NAME}-${CI_COMMIT_TAG}.tar.xz"

stages:
  - "bootstrap"
  - "build"
  - "release"

.with-deps:
  image: "debian:testing"
  before_script:
    - apt -qq update
    - apt -y -qq install
        autoconf
        autoconf-archive
        automake
        autopoint
        build-essential
        docbook-xml
        gettext
        libcairo2-dev
        libgdk-pixbuf-2.0-dev
        libglib2.0-dev
        libgtk-3-dev
        libxml2-utils
        pkgconf
        uuid-dev
        valac
        yelp-tools

bootstrap:
  extends:
    - .with-deps
  stage: "bootstrap"
  script:
    - rm -rf bootstrapped
    - mkdir bootstrapped
    - tar -cf - --exclude=bootstrapped . | tar -C bootstrapped -xf -
    - (cd bootstrapped && NOCONFIGURE=1 ./autogen.sh)
  artifacts:
    paths:
      - bootstrapped/

build-distcheck:
  extends:
    - .with-deps
  stage: "build"
  script:
    - apt -y -qq install git
    - (cd bootstrapped && ./configure --enable-maintainer-mode)
    - make -C bootstrapped distcheck V=1
  artifacts:
    paths:
      - "bootstrapped/*.tar.xz"
