/* Automatically generated by po2tbl.sed from telegnome.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"TeleGNOME: Teletext for GNOME", 2},
  {"Page:", 3},
  {"Page number", 4},
  {"Go To Page", 5},
  {"Get Previous Page", 6},
  {"Get Next Page", 7},
  {"Go to the home page", 8},
  {"Toggles auto-paging", 9},
  {"Channels", 10},
  {"TeleGNOME: %s (%s)", 11},
  {"Dirk-Jan C. Binnema <djcb@dds.nl>", 12},
  {"Arjan Scherpenisse <acscherp@wins.uva.nl>", 13},
  {"(c) 1999, 2000 Dirk-Jan C. Binnema, Arjan Scherpenisse", 14},
  {"\
Teletext for GNOME\n\
Released under the terms of the GPL", 15},
  {"Error in page entry", 16},
  {"TeleGNOME: Preferences", 17},
  {"Misc", 18},
  {"Paging interval", 19},
  {"Specifies the interval for the auto-pager, in milliseconds.", 20},
  {"Proxy server", 21},
  {"Miscelaneous", 22},
  {"Country", 23},
  {"Name", 24},
  {"Move up", 25},
  {"Move down", 26},
  {"Add...", 27},
  {"Delete", 28},
  {"Edit", 29},
  {"New/Edit Channel", 30},
  {"Description", 31},
  {"Page url", 32},
  {"Subpage url", 33},
  {"Channel Information", 34},
  {"Web server error: Wrong page number?", 35},
  {"Error making HTTP connection", 36},
  {"No connection", 37},
  {"Error using temporary file", 38},
  {"Error setting permissions on temporary file", 39},
  {"Internal error in HTTP query code", 40},
};

int _msg_tbl_length = 40;
